### ISSUE TITLE
Pipelines can't install Pytorch extensions that require torch to already be installed

### ISSUE THREAD

**Issue by WillEngler** [Garden-AI/garden#237]
There are several libraries that Eliu's group uses that assume that `torch` is installed during their install. For example, [pytorch_scatter](https://github.com/rusty1s/pytorch_scatter) or [pytorch_sparse](https://github.com/rusty1s/pytorch_sparse).

To reproduce, try and make a container with pip_dependencies=["torch==1.13.1", "torch_sparse"]

A representative traceback that Container Service spits back:

```
failed [91mPip subprocess error:   
error: subprocess-exited-with-error      
× python setup.py egg_info did not run successfully.   │
exit code: 1   ╰─> [6 lines of output]       
Traceback (most recent call last):         
File "<string>", line 2, in <module>         
File "<pip-setuptools-caller>", line 34, in <module>
File "/tmp/pip-install-0393fhlm/torch-cluster_68b8f681de9e41c6be6962c81e442ac5/setup.py", line 8, in <module>           
    import torch       
ModuleNotFoundError: No module named 'torch'
```

In Hyun's/Eliu's notebook ([link](https://colab.research.google.com/drive/1viGlpUIGmRW-kzqERj4fGzX9udEXVrXw?usp=sharing)), they install these libraries in a separate pip install after installing torch. I don't think there is a way to "sequence" our installs in Container Service.

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

**Comment by WillEngler** [comment]
Resolved as of the publishing revamp
